version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - app
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env
  main:
    build:
      context: .
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app:delegated
    ports:
      - ${PORT}:8000
    depends_on:
      - postgres
      - adminer
    networks:
      - app
    restart: always

networks:
  app:

volumes:
  pgdata: